### ISSUE TITLE
Mint: crash with 6.5 and bundled templates

### ISSUE THREAD

**Issue by BsBrabi** [SwiftGen/SwiftGen#883]
I just installed SwiftGen 6.5.0 via Mint and now I get the following error when running Swiftgen:

```
mint run SwiftGen/SwiftGen@6.5.0 config run --config scripts/swiftgen.yml
SwiftGenCLI/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/braste/.mint/packages/github.com_SwiftGen_SwiftGen/build/6.5.0/SwiftGen_SwiftGenCLI.bundle or /private/var/folders/rl/9ykwdfps5sq6gb386g34dfmd2d7tbj/T/mint/github.com_SwiftGen_SwiftGen/.build/arm64-apple-macosx/release/SwiftGen_SwiftGenCLI.bundle
[1]    92911 trace trap  mint run SwiftGen/SwiftGen@6.5.0 config run --config scripts/swiftgen.yml
```

EDIT: It works fine when I replace SwiftGen with mthole/SwiftGen@xc13-fix

**Comment by AF-cgi** [comment]
It's not possible to use the standard templates. If you use your own template, then it's possible to work with the new version 6.5.0.

**Comment by djbe** [comment]
Weird, is Mint deleting part of the build results (the resource bundle)? Will have to investigate.
@BsBrabi that fork you mentioned is for SwiftGen 6.4, it's behind a version.

Note: I though some people had been using SwiftGen develop via Mint for a while, surprised this is coming up now 😅

**Comment by BsBrabi** [comment]
I tried both develop branch and 6.5.0 release, but I still get a similar error:

```
SwiftGenCLI/resource_bundle_accessor.swift:11: Fatal error: could not load resource bundle: from /Users/braste/.mint/packages/github.com_SwiftGen_SwiftGen/build/develop/SwiftGen_SwiftGenCLI.bundle or /private/var/folders/rl/9ykwdfps5sq6gb386g34dfmd2d7tbj/T/mint/github.com_SwiftGen_SwiftGen/.build/x86_64-apple-macosx/release/SwiftGen_SwiftGenCLI.bundle
[1]    41399 illegal hardware instruction  mint run SwiftGen/SwiftGen@develop config run --config scripts/swiftgen.yml
```

It looks exactly like #878 but the only working solution for me is the fork `mthole/SwiftGen@xc13-fix`.

@AF-cgi What do you mean by "use your own template"? Is there a breaking change between 6.4 and 6.5?

**Comment by djbe** [comment]
Develop and 6.5 both currently point to the same code, 6.5 was released yesterday.
In #878 there's a Mint user that mentions using `develop`, and it works for them, which is why I'm a bit surprised it isn't working now.

There's no breaking change in 6.5, what happened is that we internally switched how we bundle templates. It seems like Mint does not handle our use case yet.

**Comment by BsBrabi** [comment]
I think you are right, I just downloaded the 6.5.0 binary from the release page and it works fine.

**Comment by djbe** [comment]
Yep, it's a bug (afaik) in Mint. I've created an issue there: https://github.com/yonaskolb/Mint/issues/223

**Comment by BsBrabi** [comment]
Thanks for the fix, v6.5.1 works again.
